version: "3.1"

services:
  proxy:
    image: 'nginx:latest' 
    command: "service nginx start"
    ports: 
      - "8080:8080"
    platform: linux/amd64
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    extra_hosts:
      - "localhost:host-gateway"
    
